# Config Service Configuration
spring.application.name=config-service
server.port=8888

# Configuration repository avec chemin ABSOLU COMPLET
spring.cloud.config.server.native.search-locations=file:///home/ellayli/enset_CCN/s5/system destribue/tp3/banking-microservices-app/config-repo

# Activer le profil native
spring.profiles.active=native
