# Application name
spring.application.name=gateway-service

# Server port
server.port=8080

# ========== Configuration Statique des Routes ==========
# Route vers customer-service
spring.cloud.gateway.routes[0].id=customer-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/customers/**

# Route vers inventory-service
spring.cloud.gateway.routes[1].id=inventory-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/products/**

# ========== CONFIGURATION DYNAMIQUE DES ROUTES ==========
# Activer la découverte automatique des services
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true


# Logs pour debug
logging.level.org.springframework.cloud.gateway=DEBUG