# Application name
spring.application.name=customer-service

# Server port
server.port=8081

# H2 Database configuration
spring.datasource.url=jdbc:h2:mem:customer-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Eureka Client Configuration
# Activer Eureka Client
eureka.client.enabled=true

# URL du serveur Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# S'enregistrer auprès d'Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Nom de l'instance
eureka.instance.instance-id=${spring.application.name}:${random.value}