# Application name
spring.application.name=inventory-service

# Server port (différent de customer-service qui est sur 8081)
server.port=8082

# H2 Database configuration
spring.datasource.url=jdbc:h2:mem:inventory-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Désactiver Eureka temporairement
eureka.client.enabled=false